In [1]:
import pandas as pd

In [2]:
CA_videos = pd.read_csv("videos/CAvideos.csv.zst")
DE_videos = pd.read_csv("videos/DEvideos.csv.zst")
FR_videos = pd.read_csv("videos/FRvideos.csv.zst")
IN_videos = pd.read_csv("videos/INvideos.csv.zst")
US_videos = pd.read_csv("videos/USvideos.csv.zst")
GB_videos = pd.read_csv("videos/GBvideos.csv.zst")
JP_videos = pd.read_csv("videos/JPvideos.csv.zst", encoding='utf-8', encoding_errors= 'replace')
MX_videos = pd.read_csv("videos/MXvideos.csv.zst", encoding='utf-8', encoding_errors= 'replace')
RU_videos = pd.read_csv("videos/RUvideos.csv.zst", encoding='utf-8', encoding_errors= 'replace')
KR_videos = pd.read_csv("videos/KRvideos.csv.zst", encoding='utf-8', encoding_errors= 'replace')

### 1. Create a single dataframe with the concatenation of all input csv files, adding a column called country

In [3]:
CA_videos['country']='CA'
DE_videos['country']='DE'
FR_videos['country']='FR'
GB_videos['country']='GB'
IN_videos['country']='IN'
JP_videos['country']='JP'
KR_videos['country']='KR'
MX_videos['country']='MX'
RU_videos['country']='RU'
US_videos['country']='US'
lista= (CA_videos, DE_videos, FR_videos, GB_videos, IN_videos, JP_videos, KR_videos, MX_videos, RU_videos, US_videos)
unione= pd.concat(lista, ignore_index=True)
unione

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country
0,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787425,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,CA
1,0dBIkQ4Mz1M,17.14.11,PLUSH - Bad Unboxing Fan Mail,iDubbbzTV,23,2017-11-13T17:00:00.000Z,"plush|""bad unboxing""|""unboxing""|""fan mail""|""id...",1014651,127794,1688,13030,https://i.ytimg.com/vi/0dBIkQ4Mz1M/default.jpg,False,False,False,STill got a lot of packages. Probably will las...,CA
2,5qpjK5DgCt4,17.14.11,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12T19:05:24.000Z,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146035,5339,8181,https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg,False,False,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...,CA
3,d380meD0W0M,17.14.11,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12T18:01:41.000Z,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095828,132239,1989,17518,https://i.ytimg.com/vi/d380meD0W0M/default.jpg,False,False,False,I know it's been a while since we did this sho...,CA
4,2Vv-BfVoq4g,17.14.11,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,10,2017-11-09T11:04:14.000Z,"edsheeran|""ed sheeran""|""acoustic""|""live""|""cove...",33523622,1634130,21082,85067,https://i.ytimg.com/vi/2Vv-BfVoq4g/default.jpg,False,False,False,🎧: https://ad.gt/yt-perfect\n💰: https://atlant...,CA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375937,BZt0qjTWNhw,18.14.06,The Cat Who Caught the Laser,AaronsAnimals,15,2018-05-18T13:00:04.000Z,"aarons animals|""aarons""|""animals""|""cat""|""cats""...",1685609,38160,1385,2657,https://i.ytimg.com/vi/BZt0qjTWNhw/default.jpg,False,False,False,The Cat Who Caught the Laser - Aaron's Animals,US
375938,1h7KV2sjUWY,18.14.06,True Facts : Ant Mutualism,zefrank1,22,2018-05-18T01:00:06.000Z,[none],1064798,60008,382,3936,https://i.ytimg.com/vi/1h7KV2sjUWY/default.jpg,False,False,False,NaN,US
375939,D6Oy4LfoqsU,18.14.06,I GAVE SAFIYA NYGAARD A PERFECT HAIR MAKEOVER ...,Brad Mondo,24,2018-05-18T17:34:22.000Z,I gave safiya nygaard a perfect hair makeover ...,1066451,48068,1032,3992,https://i.ytimg.com/vi/D6Oy4LfoqsU/default.jpg,False,False,False,I had so much fun transforming Safiyas hair in...,US
375940,oV0zkMe1K8s,18.14.06,How Black Panther Should Have Ended,How It Should Have Ended,1,2018-05-17T17:00:04.000Z,"Black Panther|""HISHE""|""Marvel""|""Infinity War""|...",5660813,192957,2846,13088,https://i.ytimg.com/vi/oV0zkMe1K8s/default.jpg,False,False,False,How Black Panther Should Have EndedWatch More ...,US
375941,ooyjaVdt-jA,18.14.06,Official Call of Duty®: Black Ops 4 — Multipla...,Call of Duty,20,2018-05-17T17:09:38.000Z,"call of duty|""cod""|""activision""|""Black Ops 4""",10306119,357079,212976,144795,https://i.ytimg.com/vi/ooyjaVdt-jA/default.jpg,False,False,False,Call of Duty: Black Ops 4 Multiplayer raises t...,US

### 2. Extract all videos that have no tag

In [4]:
no_tags = unione[unione["tags"] == "[none]"]
no_tags

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country
41,JwboxqDylgg,17.14.11,Canada Soccer's Women's National Team v USA In...,Canada Soccer,17,2017-11-13T05:53:49.000Z,[none],36311,277,28,13,https://i.ytimg.com/vi/JwboxqDylgg/default.jpg,False,False,False,Canada Soccer's Women's National Team face riv...,CA
58,9B-q8h31Bpk,17.14.11,John Oliver Tackles Louis C.K. And Donald Trum...,TV Shows,22,2017-11-13T04:49:26.000Z,[none],106029,1270,101,181,https://i.ytimg.com/vi/9B-q8h31Bpk/default.jpg,False,False,False,"John Oliver on News, Politics ...",CA
78,1UE5Dq1rvUA,17.14.11,Taylor Swift Perform Ready For It - SNL,Ken Reactz,24,2017-11-12T05:18:02.000Z,[none],320964,8069,285,717,https://i.ytimg.com/vi/1UE5Dq1rvUA/default.jpg,False,False,False,Thanks for watching please subscribe and subsc...,CA
86,pmJQ4KwliX4,17.14.11,"LATEST Q POSTS: ROTHSCHILDS, HOUSE OF SAUD, lL...",James Munder,2,2017-11-12T21:25:40.000Z,[none],116820,1503,139,1066,https://i.ytimg.com/vi/pmJQ4KwliX4/default.jpg,False,False,False,https://pastebin.ca/3930472\n\nSupport My Chan...,CA
98,lHcXhBojpeQ,17.14.11,三屆TVB視帝，拋棄10年青梅竹馬髮妻，為娶小三還不惜與母絕交！,明星百曉生,22,2017-11-12T12:49:50.000Z,[none],88061,47,58,17,https://i.ytimg.com/vi/lHcXhBojpeQ/default.jpg,False,False,False,NaN,CA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375815,VGykknw9eCM,18.14.06,"Made Defiant: The Mixtape ft. Neymar Jr., Kane...",Beats by Dre,10,2018-06-07T07:01:06.000Z,[none],3577614,12318,1345,1414,https://i.ytimg.com/vi/VGykknw9eCM/default.jpg,False,False,False,"When your time comes, you have two choices. Yo...",US
375819,fAIX12F6958,18.14.06,Bumblebee (2018) - Official Teaser Trailer - P...,Paramount Pictures,1,2018-06-05T07:00:01.000Z,[none],19864779,228670,16420,46318,https://i.ytimg.com/vi/fAIX12F6958/default.jpg,False,False,False,Every adventure has a beginning. Watch the off...,US
375865,gS1DbvHHVH0,18.14.06,Going in to brain surgery,Simone Giertz,28,2018-05-30T14:22:13.000Z,[none],1635301,120791,1098,20711,https://i.ytimg.com/vi/gS1DbvHHVH0/default.jpg,False,False,False,We’ll post an update on Instagram and Twitter ...,US
375873,E4c7EE8_IX0,18.14.06,Weezer - Africa,weezer,10,2018-05-29T12:00:11.000Z,[none],4682557,115240,5069,9170,https://i.ytimg.com/vi/E4c7EE8_IX0/default.jpg,False,False,False,Stream + download the song: http://fanlink.to/...,US
375938,1h7KV2sjUWY,18.14.06,True Facts : Ant Mutualism,zefrank1,22,2018-05-18T01:00:06.000Z,[none],1064798,60008,382,3936,https://i.ytimg.com/vi/1h7KV2sjUWY/default.jpg,False,False,False,NaN,US

### 3. For each channel, determine the total number of views

In [5]:
tot_views = unione.groupby("channel_title")[["views"]].sum()
tot_views

                          views
channel_title
! 세상에 무슨일이              3942977
!!8時だよ面白ネタ大集合             50207
!BTS・TWICE まとめ             7310
!Los amorosos Virales¡     6069
!t Live                  240038
...                         ...
５分でできる DIY               272607
ＢＡＳＨｔｖ                   116292
Ｋのフィッシングちゃんねる             37165
ＷＡＪＯＩＫＡ                  424129
💜Sandrea                 347155

[37824 rows x 1 columns]

### 4. Save all rows with disabled comments and disabled ratings, or that have video_error_or_removed in a new dataframe called excluded, and remove those rows from the original dataframe

In [6]:
excluded = unione[((unione["comments_disabled"] == True) &
    (unione["ratings_disabled"] == True)) |
    (unione["video_error_or_removed"] == True)
    ]
unione_excluded = unione.drop(excluded.index)
unione_excluded

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country
0,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787425,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,CA
1,0dBIkQ4Mz1M,17.14.11,PLUSH - Bad Unboxing Fan Mail,iDubbbzTV,23,2017-11-13T17:00:00.000Z,"plush|""bad unboxing""|""unboxing""|""fan mail""|""id...",1014651,127794,1688,13030,https://i.ytimg.com/vi/0dBIkQ4Mz1M/default.jpg,False,False,False,STill got a lot of packages. Probably will las...,CA
2,5qpjK5DgCt4,17.14.11,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12T19:05:24.000Z,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146035,5339,8181,https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg,False,False,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...,CA
3,d380meD0W0M,17.14.11,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12T18:01:41.000Z,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095828,132239,1989,17518,https://i.ytimg.com/vi/d380meD0W0M/default.jpg,False,False,False,I know it's been a while since we did this sho...,CA
4,2Vv-BfVoq4g,17.14.11,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,10,2017-11-09T11:04:14.000Z,"edsheeran|""ed sheeran""|""acoustic""|""live""|""cove...",33523622,1634130,21082,85067,https://i.ytimg.com/vi/2Vv-BfVoq4g/default.jpg,False,False,False,🎧: https://ad.gt/yt-perfect\n💰: https://atlant...,CA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375937,BZt0qjTWNhw,18.14.06,The Cat Who Caught the Laser,AaronsAnimals,15,2018-05-18T13:00:04.000Z,"aarons animals|""aarons""|""animals""|""cat""|""cats""...",1685609,38160,1385,2657,https://i.ytimg.com/vi/BZt0qjTWNhw/default.jpg,False,False,False,The Cat Who Caught the Laser - Aaron's Animals,US
375938,1h7KV2sjUWY,18.14.06,True Facts : Ant Mutualism,zefrank1,22,2018-05-18T01:00:06.000Z,[none],1064798,60008,382,3936,https://i.ytimg.com/vi/1h7KV2sjUWY/default.jpg,False,False,False,NaN,US
375939,D6Oy4LfoqsU,18.14.06,I GAVE SAFIYA NYGAARD A PERFECT HAIR MAKEOVER ...,Brad Mondo,24,2018-05-18T17:34:22.000Z,I gave safiya nygaard a perfect hair makeover ...,1066451,48068,1032,3992,https://i.ytimg.com/vi/D6Oy4LfoqsU/default.jpg,False,False,False,I had so much fun transforming Safiyas hair in...,US
375940,oV0zkMe1K8s,18.14.06,How Black Panther Should Have Ended,How It Should Have Ended,1,2018-05-17T17:00:04.000Z,"Black Panther|""HISHE""|""Marvel""|""Infinity War""|...",5660813,192957,2846,13088,https://i.ytimg.com/vi/oV0zkMe1K8s/default.jpg,False,False,False,How Black Panther Should Have EndedWatch More ...,US
375941,ooyjaVdt-jA,18.14.06,Official Call of Duty®: Black Ops 4 — Multipla...,Call of Duty,20,2018-05-17T17:09:38.000Z,"call of duty|""cod""|""activision""|""Black Ops 4""",10306119,357079,212976,144795,https://i.ytimg.com/vi/ooyjaVdt-jA/default.jpg,False,False,False,Call of Duty: Black Ops 4 Multiplayer raises t...,US

### 5. Add a like_ratio column storing the ratio between the number of likes and of dislikes

In [7]:
unione_excluded["like_ratio"] = unione_excluded["likes"]/unione_excluded["dislikes"]

### 6 Cluster the publish time into 10-minute intervals (e.g. from 02:20 to 02:30)

In [8]:
unione_excluded["publish_time"] = pd.to_datetime(unione_excluded["publish_time"])
unione_excluded["range_10min"] = unione_excluded["publish_time"].dt.floor("10min").dt.time
unione_excluded.head()

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country,like_ratio,range_10min
0,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10 17:00:03+00:00,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787425,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,CA,18.135076,17:00:00
1,0dBIkQ4Mz1M,17.14.11,PLUSH - Bad Unboxing Fan Mail,iDubbbzTV,23,2017-11-13 17:00:00+00:00,"plush|""bad unboxing""|""unboxing""|""fan mail""|""id...",1014651,127794,1688,13030,https://i.ytimg.com/vi/0dBIkQ4Mz1M/default.jpg,False,False,False,STill got a lot of packages. Probably will las...,CA,75.707346,17:00:00
2,5qpjK5DgCt4,17.14.11,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12 19:05:24+00:00,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146035,5339,8181,https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg,False,False,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...,CA,27.352500,19:00:00
3,d380meD0W0M,17.14.11,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12 18:01:41+00:00,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095828,132239,1989,17518,https://i.ytimg.com/vi/d380meD0W0M/default.jpg,False,False,False,I know it's been a while since we did this sho...,CA,66.485168,18:00:00
4,2Vv-BfVoq4g,17.14.11,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,10,2017-11-09 11:04:14+00:00,"edsheeran|""ed sheeran""|""acoustic""|""live""|""cove...",33523622,1634130,21082,85067,https://i.ytimg.com/vi/2Vv-BfVoq4g/default.jpg,False,False,False,🎧: https://ad.gt/yt-perfect\n💰: https://atlant...,CA,77.513044,11:00:00

### 7 For each interval, determine the number of videos, average number of likes and of dislikes.

In [9]:
union_cluster= unione_excluded.groupby("range_10min").agg({"video_id": "count" ,
                                                  "likes": "mean",
                                                  "dislikes": "mean"})
union_cluster

             video_id         likes     dislikes
range_10min
00:00:00         2897  61288.115637  3808.149465
00:10:00         1509  22748.138502  1449.836315
00:20:00         1241  21378.280419  1072.344883
00:30:00         1614  36853.560719   955.890954
00:40:00         1269  42198.623325  1909.301812
...               ...           ...          ...
23:10:00         1554  22783.840412  1110.168597
23:20:00         1438  30696.510431  1177.020862
23:30:00         1666  18159.173469   874.184874
23:40:00         1466  45736.581855  9341.549795
23:50:00         1269  10853.743893   505.701340

[144 rows x 3 columns]

### 8. For each tag, determine the number of videos

In [10]:
no_tags2 = unione_excluded[unione_excluded["tags"] == "[none]"]
unione_notags = unione_excluded.drop(no_tags2.index)
tags = unione_notags["tags"].str.replace('"', '').str.split(r"[|/]")
tags2= tags.explode()
tot_tags = tags2.value_counts()
tot_tags

tags
funny                          15039
comedy                         12351
2018                           11896
news                            6363
music                           5909
                               ...
American culture                   1
America vs Germany                 1
melonenbirne                       1
crayola asos crayons makeup        1
crayola makeup review              1
Name: count, Length: 849267, dtype: int64

### 9. Find the tags with the largest number of videos

In [11]:
tot_tags.head(10)

tags
funny         15039
comedy        12351
2018          11896
news           6363
music          5909
2017           5903
video          5612
humor          5057
television     4170
show           4146
Name: count, dtype: int64

### 10. For each (tag,country) pair, compute average ratio like/dislikes

In [12]:
unione_tags = (unione_notags.assign(tags = unione_notags["tags"].str.replace('"','').str.split(r"[|/]")).explode("tags").reset_index(drop=True))
unione_tags.groupby(['country','tags'])['like_ratio'].mean()
unione_tags

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country,like_ratio,range_10min
0,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10 17:00:03+00:00,Eminem,17158579,787425,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,CA,18.135076,17:00:00
1,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10 17:00:03+00:00,Walk,17158579,787425,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,CA,18.135076,17:00:00
2,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10 17:00:03+00:00,On,17158579,787425,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,CA,18.135076,17:00:00
3,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10 17:00:03+00:00,Water,17158579,787425,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,CA,18.135076,17:00:00
4,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10 17:00:03+00:00,Aftermath,17158579,787425,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,CA,18.135076,17:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6430513,oV0zkMe1K8s,18.14.06,How Black Panther Should Have Ended,How It Should Have Ended,1,2018-05-17 17:00:04+00:00,ending explained,5660813,192957,2846,13088,https://i.ytimg.com/vi/oV0zkMe1K8s/default.jpg,False,False,False,How Black Panther Should Have EndedWatch More ...,US,67.799368,17:00:00
6430514,ooyjaVdt-jA,18.14.06,Official Call of Duty®: Black Ops 4 — Multipla...,Call of Duty,20,2018-05-17 17:09:38+00:00,call of duty,10306119,357079,212976,144795,https://i.ytimg.com/vi/ooyjaVdt-jA/default.jpg,False,False,False,Call of Duty: Black Ops 4 Multiplayer raises t...,US,1.676616,17:00:00
6430515,ooyjaVdt-jA,18.14.06,Official Call of Duty®: Black Ops 4 — Multipla...,Call of Duty,20,2018-05-17 17:09:38+00:00,cod,10306119,357079,212976,144795,https://i.ytimg.com/vi/ooyjaVdt-jA/default.jpg,False,False,False,Call of Duty: Black Ops 4 Multiplayer raises t...,US,1.676616,17:00:00
6430516,ooyjaVdt-jA,18.14.06,Official Call of Duty®: Black Ops 4 — Multipla...,Call of Duty,20,2018-05-17 17:09:38+00:00,activision,10306119,357079,212976,144795,https://i.ytimg.com/vi/ooyjaVdt-jA/default.jpg,False,False,False,Call of Duty: Black Ops 4 Multiplayer raises t...,US,1.676616,17:00:00
6430517,ooyjaVdt-jA,18.14.06,Official Call of Duty®: Black Ops 4 — Multipla...,Call of Duty,20,2018-05-17 17:09:38+00:00,Black Ops 4,10306119,357079,212976,144795,https://i.ytimg.com/vi/ooyjaVdt-jA/default.jpg,False,False,False,Call of Duty: Black Ops 4 Multiplayer raises t...,US,1.676616,17:00:00

### 11. For each (trending_date, country) pair, the video with the largest number of views

In [13]:
id_views = unione_tags.groupby(['trending_date','country'])['views'].idxmax()
id_views = unione_tags.loc[id_views]
id_views[['trending_date','country','title']]

,trending_date,country,title
64484,17.01.12,CA,Marvel Studios' Avengers: Infinity War Officia...
857581,17.01.12,DE,Marvel Studios' Avengers: Infinity War Officia...
1576690,17.01.12,FR,Avengers: Infinity War Trailer Tease
2181941,17.01.12,GB,"Luis Fonsi, Demi Lovato - Échame La Culpa"
2873965,17.01.12,IN,Marvel Studios' Avengers: Infinity War Officia...
...,...,...,...
3736826,18.31.05,JP,Maroon 5 - Girls Like You ft. Cardi B
4285657,18.31.05,KR,[MV] AOA _ Bingle Bangle(빙글뱅글)
4870510,18.31.05,MX,"Cardi B, Bad Bunny & J Balvin - I Like It [Off..."
5567125,18.31.05,RU,[BadComedian] - Движение Вверх (Плагиат или ве...
6372713,18.31.05,US,Childish Gambino - This Is America (Official V...

### 12. Divide trending_date into three columns: year, month, day

In [14]:
unione_excluded['day'] = unione_excluded['publish_time'].dt.day
unione_excluded['month'] = unione_excluded['publish_time'].dt.month
unione_excluded['year'] = unione_excluded['publish_time'].dt.year

### 13. For each (month, country) pair, the video with the largest number of views

In [15]:
id_views2 = unione_excluded.groupby(['month','country'])['views'].idxmax()
id_views2 = unione_excluded.loc[id_views2]
id_views2[['month','country','title']]

        month country                                              title
11214       1      CA  Bruno Mars - Finesse (Remix) [Feat. Cardi B] [...
51930       1      DE  Bruno Mars - Finesse (Remix) [Feat. Cardi B] [...
92853       1      FR  Bruno Mars - Finesse (Remix) [Feat. Cardi B] [...
143607      1      GB           Ozuna x Romeo Santos - El Farsante Remix
173405      1      IN     Taylor Swift - End Game ft. Ed Sheeran, Future
...       ...     ...                                                ...
166769     12      IN  YouTube Rewind: The Shape of 2017 | #YouTubeRe...
224092     12      KR  YouTube Rewind: The Shape of 2017 | #YouTubeRe...
259064     12      MX  YouTube Rewind: The Shape of 2017 | #YouTubeRe...
299087     12      RU  YouTube Rewind: The Shape of 2017 | #YouTubeRe...
341174     12      US  YouTube Rewind: The Shape of 2017 | #YouTubeRe...

[111 rows x 3 columns]

### 14. Read all json files with the video categories

In [16]:
CA_category = pd.read_json("CA_category_id.json")
DE_category = pd.read_json("DE_category_id.json")
FR_category = pd.read_json("FR_category_id.json")
IN_category = pd.read_json("IN_category_id.json")
US_category = pd.read_json("US_category_id.json")
GB_category = pd.read_json("GB_category_id.json")
JP_category = pd.read_json("JP_category_id.json")
MX_category = pd.read_json("MX_category_id.json")
RU_category = pd.read_json("RU_category_id.json")
KR_category = pd.read_json("KR_category_id.json")

lista_category = (CA_category, DE_category, FR_category, GB_category, IN_category, JP_category, KR_category, MX_category, RU_category, US_category)
unione_category = pd.concat(lista_category, ignore_index=True)
unione_category

,kind,etag,items
0,youtube#videoCategoryListResponse,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/1v2mrzYSYG6onNLt2...","{'kind': 'youtube#videoCategory', 'etag': '""ld..."
1,youtube#videoCategoryListResponse,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/1v2mrzYSYG6onNLt2...","{'kind': 'youtube#videoCategory', 'etag': '""ld..."
2,youtube#videoCategoryListResponse,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/1v2mrzYSYG6onNLt2...","{'kind': 'youtube#videoCategory', 'etag': '""ld..."
3,youtube#videoCategoryListResponse,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/1v2mrzYSYG6onNLt2...","{'kind': 'youtube#videoCategory', 'etag': '""ld..."
4,youtube#videoCategoryListResponse,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/1v2mrzYSYG6onNLt2...","{'kind': 'youtube#videoCategory', 'etag': '""ld..."
...,...,...,...
306,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
307,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
308,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
309,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
310,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."

In [17]:
unione_category_normalized = pd.json_normalize(unione_category['items'])

unione_category_normalized = unione_category_normalized.rename(columns={'snippet.channelId': 'channelId',
                                                                        'snippet.title': 'title',
                                                                        'snippet.assignable': 'assignable'})

unione_category_normalized

,kind,etag,id,channelId,title,assignable
0,youtube#videoCategory,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/Xy1mB4_yLrHy_BmKm...",1,UCBR8-60-B28hp2BmDPdntcQ,Film & Animation,True
1,youtube#videoCategory,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/UZ1oLIIz2dxIhO45Z...",2,UCBR8-60-B28hp2BmDPdntcQ,Autos & Vehicles,True
2,youtube#videoCategory,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/nqRIq97-xe5XRZTxb...",10,UCBR8-60-B28hp2BmDPdntcQ,Music,True
3,youtube#videoCategory,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/HwXKamM1Q20q9BN-o...",15,UCBR8-60-B28hp2BmDPdntcQ,Pets & Animals,True
4,youtube#videoCategory,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/9GQMSRjrZdHeb1OEM...",17,UCBR8-60-B28hp2BmDPdntcQ,Sports,True
...,...,...,...,...,...,...
306,youtube#videoCategory,"""m2yskBQFythfE4irbTIeOgYYfBU/N1TrDFLRppxZgBowC...",40,UCBR8-60-B28hp2BmDPdntcQ,Sci-Fi/Fantasy,False
307,youtube#videoCategory,"""m2yskBQFythfE4irbTIeOgYYfBU/7UMGi6zRySqXopr_r...",41,UCBR8-60-B28hp2BmDPdntcQ,Thriller,False
308,youtube#videoCategory,"""m2yskBQFythfE4irbTIeOgYYfBU/RScXhi324h8usyIet...",42,UCBR8-60-B28hp2BmDPdntcQ,Shorts,False
309,youtube#videoCategory,"""m2yskBQFythfE4irbTIeOgYYfBU/0n9MJVCDLpA8q7aiG...",43,UCBR8-60-B28hp2BmDPdntcQ,Shows,False
310,youtube#videoCategory,"""m2yskBQFythfE4irbTIeOgYYfBU/x5NxSf5fz8hn4loSN...",44,UCBR8-60-B28hp2BmDPdntcQ,Trailers,False

### 15. For each country, determine how many videos have a category that is not assignable.

In [18]:
unione_category_normalized['id'] = unione_category_normalized['id'].astype(int)
unione_join = pd.merge(unione_excluded, unione_category_normalized, left_on = 'category_id', right_on = 'id', how='left')
unione_join_false = unione_join[unione_join['assignable'] == False]
unione_join_false.groupby('country')['video_id'].count()

country
CA    1300
DE    1100
FR    1120
GB     200
IN    2210
KR    1670
MX      30
RU    1950
US     570
Name: video_id, dtype: int64